services:
  db:
    build: ./movies_list
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app
    environment:
      - TMDB_API_KEY="api-key"
  web:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  db-data: