version: '3'
services:
  db:
    build: ./movies_list
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app
  web:
    build: ./frontend
    ports:
      - "3000:3000"


volumes:
  db-data: