# Generated by Django 4.2.2 on 2023-06-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tmdb_id', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=12)),
                ('popularity', models.FloatField()),
                ('release_date', models.CharField(max_length=12)),
                ('runtime', models.IntegerField()),
                ('overview', models.CharField(max_length=1000)),
            ],
        ),
    ]
