# Generated by Django 4.2.2 on 2023-07-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_movie_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
    ]
