# Generated by Django 4.2.2 on 2023-09-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_tmdb_id_alter_tag_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
